name: IS2view
channels:
  - conda-forge
dependencies:
  - h5netcdf
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - notebook
  - panel
  - pip
  - python>=3.6
  - numpy>=1.21
  - rioxarray
  - setuptools_scm
  - xarray
