name: IS2view
channels:
  - conda-forge
dependencies:
  - boto3
  - bottleneck
  - dask
  - geopandas
  - h5netcdf
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - netCDF4
  - notebook
  - pip
  - python>=3.6
  - numpy>=1.21
  - rioxarray
  - s3fs
  - setuptools_scm
  - xarray
  - zarr
