name: is2view-docs
channels:
  - conda-forge
dependencies:
  - boto3
  - docutils<0.18
  - graphviz
  - ipywidgets
  - matplotlib
  - notebook
  - numpy
  - numpydoc
  - pip
  - python>=3.6
  - sphinx
  - sphinx-argparse
  - sphinx_rtd_theme
  - texlive-core
  - pip:
    - ..
